// src/features/capture/index.tsx
import { useEffect, useRef, useState } from "react";
import { useScreenCapture } from "@/app/screen-capture";
import { useNavbarStore } from "../navbar/store";
import { useResizeObserver } from "@/app/resize-observer";

export function Capture() {
  const documentRef = useRef<HTMLElement>(document.documentElement);
  const { cast, setCast } = useNavbarStore((state) => state);
  const { start, stop, ref, running } = useScreenCapture();
  const [height, setHeight] = useState<number>(0);

  useEffect(() => {
    if (cast && !running) start(setCast, () => setCast(false));
    if (!cast && running) stop();
  }, [cast]);

  // Resize the video element to always be 100vh minus the navbar
  // or any elements above the capture window.
  useResizeObserver({
    ref: documentRef,
    onResize: () => {
      if (ref.current) {
        setHeight(() =>
          ref.current
            ? Array.from(ref.current.getClientRects()).reduce((accum, curr) => accum + curr.y, 0)
            : 0,
        );
      }
    },
  });

  return (
    <video
      ref={ref}
      className="fixed z-0 w-full overflow-hidden bg-neutral-950 opacity-50"
      style={{
        height: `calc(100vh - ${height}px)`,
      }}
      autoPlay
    ></video>
  );
}

// src/features/capture/index.svelte
<script lang="ts">
  import { createScreenCapture } from '@/app/screen-capture.svelte';
  import { navbarStore } from '../navbar/store.svelte';
  import { createResizeObserver } from '@/app/resize-observer.svelte';

  let videoElement = $state<HTMLVideoElement>();
  let height = $state(0);

  const screenCapture = createScreenCapture();

  // Watch for cast changes and handle screen capture
  $effect(() => {
    if (navbarStore.cast && !screenCapture.running) {
      screenCapture.start(
        (success) => navbarStore.setCast(success),
        () => navbarStore.setCast(false)
      );
    }
    if (!(navbarStore.cast) && screenCapture.running) {
      screenCapture.stop();
    }
  });

  // Bind video element when it's available
  $effect(() => {
    if (videoElement) {
      screenCapture.bindVideo(videoElement);
    }
  });

  // Handle resize observations
  const updateHeight = () => {
    if (videoElement) {
      const rects = Array.from(videoElement.getClientRects());
      height = rects.reduce((accum, curr) => accum + curr.y, 0);
    }
  };

  // Set up resize observer for document element
  $effect(() => {
    const documentElement = document.documentElement;
    
    const resizeObserver = createResizeObserver({
      onResize: updateHeight,
    });

    const { destroy } = resizeObserver.action(documentElement);

    return destroy;
  });
</script>

<!-- svelte-ignore a11y_media_has_caption -->
<video
  bind:this={videoElement}
  class="fixed z-0 w-full overflow-hidden bg-neutral-950 opacity-50"
  style="height: calc(100vh - {height}px)"
  autoplay
></video>
