// src/features/content/index.tsx
import { useRef } from "react";
import { escape } from "@/lib/html-escaper";
import { useNavbarStore } from "../navbar/store";
import { useContentStore } from "./store";
import { useHotkeys } from "react-hotkeys-hook";
import { getBoundsStart, resetTranscriptWindow } from "@/lib/speech-matcher";
import { useEffectInterval } from "@/app/hooks";
import { clsx } from "@/lib/css";
import { getNextSentence, getNextWordIndex, getPrevSentence } from "@/lib/word-tokenizer";
import { scroll } from "@/lib/smooth-scroll";

export function Content() {
  const { status, mirror, fontSize, margin, opacity, align, toggleEdit } = useNavbarStore(
    (state) => state,
  );
  const { text, setText, tokens, position, setPosition, setTokens } = useContentStore(
    (state) => state,
  );

  const style: React.CSSProperties = {
    fontSize: `${fontSize}px`,
    paddingLeft: `${margin}vw`,
    // Add more space to the right side for improved readability
    paddingRight: `${margin * 0.8 - Math.min(fontSize / 80, 1) * 0.4}vw`,
    opacity: opacity / 100,
    paddingTop: {
      top: "1rem",
      center: `calc(50vh - ${fontSize * 2}px)`,
      bottom: `calc(${(3 / 4) * 100}vh -  ${fontSize * 2}px)`,
    }[align],
  };

  const lastRef = useRef<null | HTMLDivElement>(null);

  useEffectInterval(
    () => {
      if (status !== "editing") {
        if (lastRef.current && position.end > 0) {
          scroll({
            top: {
              top: lastRef.current.offsetTop - fontSize,
              center:
                lastRef.current.offsetTop -
                document.documentElement.clientHeight / 2 +
                fontSize * 2,
              bottom:
                lastRef.current.offsetTop -
                (3 / 4) * document.documentElement.clientHeight +
                fontSize * 2,
            }[align],
            behavior: "smooth",
          });
        } else {
          scroll({
            top: 0,
            behavior: "smooth",
          });
        }
      }
    },
    status === "started" ? 1000 : null,
  );

  // Overwrite ctrl+a to allow text selection without also selecting inputs.
  const mainRef = useRef<HTMLElement | null>(null);
  const textAreaRef = useRef<HTMLTextAreaElement | null>(null);
  useHotkeys(
    "ctrl+a",
    () => {
      if (textAreaRef.current) {
        textAreaRef.current.focus();
        textAreaRef.current.select();
      } else if (mainRef.current) {
        const selection = window.getSelection();
        if (selection) {
          const range = document.createRange();
          range.selectNodeContents(mainRef.current);
          selection.removeAllRanges();
          selection.addRange(range);
        }
      }
    },
    { preventDefault: true },
    [],
  );

  useHotkeys(
    "esc",
    () => (toggleEdit(), setTokens()),
    {
      enableOnFormTags: ["textarea"],
      enabled: status === "editing",
    },
    [toggleEdit, setTokens],
  );

  useHotkeys(
    ["ArrowLeft", "ArrowUp", "PageUp"],
    () => {
      const token = getPrevSentence(tokens, position.search);
      if (token) {
        const selectedPosition = token.index - 1;
        const boundStart = getBoundsStart(tokens, selectedPosition);
        setPosition({
          start: selectedPosition,
          end: selectedPosition,
          search: selectedPosition,
          ...(boundStart !== undefined && { bounds: boundStart }),
        });
        resetTranscriptWindow();
      }
    },
    { enabled: status !== "editing" },
    [tokens, position.search, getPrevSentence, getBoundsStart, setPosition],
  );

  useHotkeys(
    ["ArrowRight", "ArrowDown", "PageDown"],
    () => {
      const token = getNextSentence(tokens, position.search);
      if (token) {
        const selectedPosition = token.index - 1;
        const boundStart = getBoundsStart(tokens, selectedPosition);
        setPosition({
          start: selectedPosition,
          end: selectedPosition,
          search: selectedPosition,
          ...(boundStart !== undefined && { bounds: boundStart }),
        });
        resetTranscriptWindow();
      }
    },
    { enabled: status !== "editing" },
    [tokens, position.search, getPrevSentence, getBoundsStart, setPosition],
  );

  return (
    <main ref={mainRef}>
      {status === "editing" ? (
        <div className="grid grid-cols-1 grid-rows-1">
          {/* Use an invisible div to force an increase in textarea sizing.
              This should have exactly the same size and properties as the textarea. */}
          <div className="content invisible col-start-1 row-start-1" style={style}>
            {text}
          </div>
          <textarea
            ref={textAreaRef}
            className="content col-start-1 row-start-1"
            style={{ ...style, cursor: "text", overflow: "hidden" }}
            value={text}
            onChange={(e) => setText(e.target.value || "")}
            placeholder="Enter your content here..."
          />
        </div>
      ) : (
        <div
          className={clsx("content select-none", status === "started" ? "content-transition" : "")}
          style={{
            ...style,
            transform: `scaleX(${mirror ? "-1" : "1"})`,
          }}
        >
          {tokens.map((token, index) => (
            <span
              // Position ref a little after the end index to scroll past line breaks and punctuation.
              {...(index === Math.min(getNextWordIndex(tokens, position.end), tokens.length - 1)
                ? { ref: lastRef }
                : {})}
              key={token.index}
              onClick={() => {
                const selectedPosition = index - 1;
                const bounds = getBoundsStart(tokens, selectedPosition);
                setPosition({
                  start: selectedPosition,
                  search: selectedPosition,
                  end: selectedPosition,
                  ...(bounds !== undefined && {
                    bounds: Math.min(bounds, tokens.length),
                  }),
                });
              }}
              className={
                token.index <= position.start
                  ? "final-transcript"
                  : token.index <= position.end
                    ? "interim-transcript"
                    : status === "started" && token.index > position.bounds + 20
                      ? "opacity-40"
                      : status === "started" && token.index > position.bounds + 10
                        ? "opacity-60"
                        : status === "started" && token.index > position.bounds
                          ? "opacity-80"
                          : ""
              }
              dangerouslySetInnerHTML={{
                __html: escape(token.value).replace(/\n/g, "<br>"),
              }}
            />
          ))}
        </div>
      )}
    </main>
  );
}

// src/features/content/index.svelte
<script lang="ts">
  import { navbarStore } from "../navbar/store.svelte";
  import { contentStore } from "./store.svelte";
  import { getBoundsStart, resetTranscriptWindow } from "@/lib/speech-matcher";
  import { getNextSentence, getPrevSentence } from "@/lib/word-tokenizer";
  import { scroll } from "@/lib/smooth-scroll";
  import Text from "@/components/Text.svelte";

  let mainRef: HTMLElement;
  let textAreaRef = $state<HTMLTextAreaElement>();
  let textComponent = $state<Text>();
  let isScrolling = $state(false);
  let lastRef = $state<HTMLSpanElement>();

  // Computed style object
  let style = $derived({
    fontSize: `${navbarStore.fontSize}px`,
    paddingLeft: `${navbarStore.margin}vw`,
    // Add more space to the right side for improved readability
    paddingRight: `${navbarStore.margin * 0.8 - Math.min(navbarStore.fontSize / 80, 1) * 0.4}vw`,
    opacity: navbarStore.opacity / 100,
    paddingTop: {
      top: "1rem",
      center: `calc(50vh - ${navbarStore.fontSize * 2}px)`,
      bottom: `calc(${(3 / 4) * 100}vh -  ${navbarStore.fontSize * 2}px)`,
    }[navbarStore.align],
  });

  // Convert to CSS strings
  let styleCSS = $derived(
    Object.entries(style)
      .map(([key, value]) => `${key.replace(/[A-Z]/g, m => '-' + m.toLowerCase())}: ${value}`)
      .join('; ')
  );

  let textareaStyleCSS = $derived(
    Object.entries({...style, cursor: 'text', overflow: 'hidden'})
      .map(([key, value]) => `${key.replace(/[A-Z]/g, m => '-' + m.toLowerCase())}: ${value}`)
      .join('; ')
  );

  // Auto-scrolling effect
  $effect(() => {
    if (navbarStore.status === "started") {
      const interval = setInterval(async () => {
        await performScroll();
      }, 2000);
      
      return () => clearInterval(interval);
    } else if (navbarStore.status !== "editing" && !isScrolling) {
      performScroll();
    }
  });

  async function performScroll() {
    if (isScrolling) return;
    
    isScrolling = true;
    try {
      if (lastRef && contentStore.position().end > 0) {
        await scroll({
          top: {
            top: lastRef.offsetTop,
            center:
              lastRef.offsetTop -
              document.documentElement.clientHeight / 2 +
              navbarStore.fontSize * 2,
            bottom:
              lastRef.offsetTop -
              (3 / 4) * document.documentElement.clientHeight +
              navbarStore.fontSize * 2,
          }[navbarStore.align],
          behavior: "smooth",
        });
      } else {
        await scroll({
          top: 0,
          behavior: "smooth",
        });
      }
    } finally {
      isScrolling = false;
    }
  }

  // Keyboard event handlers
  function handleKeyDown(event: KeyboardEvent) {
    // Ctrl+A handler
    if (event.ctrlKey && event.key === 'a') {
      event.preventDefault();
      if (textAreaRef) {
        textAreaRef.focus();
        textAreaRef.select();
      } else if (mainRef) {
        const selection = window.getSelection();
        if (selection) {
          const range = document.createRange();
          range.selectNodeContents(mainRef);
          selection.removeAllRanges();
          selection.addRange(range);
        }
      }
      return;
    }

    // Escape handler
    if (event.key === 'Escape' && navbarStore.status === "editing") {
      navbarStore.toggleEdit();
      return;
    }

    // Arrow key handlers (only when not editing)
    if (navbarStore.status !== "editing") {
      if (event.key === 'ArrowLeft' || event.key === 'ArrowUp' || event.key === 'PageUp') {
        const token = getPrevSentence(contentStore.tokens(), contentStore.position().search);
        if (token) {
          const selectedPosition = token.index - 1;
          const boundStart = getBoundsStart(contentStore.tokens(), selectedPosition);
          contentStore.setPosition({
            start: selectedPosition,
            end: selectedPosition,
            search: selectedPosition,
            ...(boundStart !== undefined && { bounds: boundStart }),
          });
          resetTranscriptWindow();
        }
        return;
      }

      if (event.key === 'ArrowRight' || event.key === 'ArrowDown' || event.key === 'PageDown') {
        const token = getNextSentence(contentStore.tokens(), contentStore.position().search);
        if (token) {
          const selectedPosition = token.index - 1;
          const boundStart = getBoundsStart(contentStore.tokens(), selectedPosition);
          contentStore.setPosition({
            start: selectedPosition,
            end: selectedPosition,
            search: selectedPosition,
            ...(boundStart !== undefined && { bounds: boundStart }),
          });
          resetTranscriptWindow();
        }
        return;
      }
    }
  }

  function handleTextAreaInput(event: Event) {
    const target = event.target as HTMLTextAreaElement;
    contentStore.setText(target.value || "");
  }
</script>

<svelte:window onkeydown={handleKeyDown} />

<main bind:this={mainRef}>
  {#if navbarStore.status === "editing"}
    <div class="grid grid-cols-1 grid-rows-1">
      <!-- Use an invisible div to force an increase in textarea sizing.
           This should have exactly the same size and properties as the textarea. -->
      <div class="content invisible col-start-1 row-start-1" style={styleCSS}>
        {contentStore.text}
      </div>
      <textarea
        bind:this={textAreaRef}
        class="content col-start-1 row-start-1"
        style={textareaStyleCSS}
        value={contentStore.text()}
        oninput={handleTextAreaInput}
        placeholder="Enter your content here..."
      ></textarea>
    </div>
  {:else}
    <Text {style} bind:lastRef bind:this={textComponent} />
  {/if}
</main>
