// src/components/DragInput.tsx
import { useCallback, useEffect, useRef } from "react";

const minValue = (value: number, min: number | string | undefined) =>
  min !== undefined ? Math.max(value, +Number(min)) : value;
const maxValue = (value: number, max: number | string | undefined) =>
  max !== undefined ? Math.min(value, +Number(max)) : value;
const stepValue = (value: number, step: number | string | undefined) =>
  step !== undefined && +Number(step) !== 0
    ? Math.round(value / +Number(step)) * +Number(step)
    : value;

const createConstraints =
  (
    min: number | string | undefined,
    max: number | string | undefined,
    step: number | string | undefined,
  ) =>
  (value: number) =>
    maxValue(minValue(stepValue(value, step), min), max);

export function DragInput({
  value,
  onValueChange,
  min,
  max,
  step,
  children,
  title,
  speed = 1,
  ...props
}: {
  value: number;
  onValueChange: (value: number) => void;
  speed?: number;
} & React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>) {
  const constrain = useCallback(createConstraints(min, max, step), [min, max, step]);
  const inputRef = useRef<HTMLInputElement>(null);

  // Use refs to store the mutable drag state
  const draggingRef = useRef<boolean>(false);
  const startValueRef = useRef<number>(0);
  const snapshotRef = useRef<number>(0);

  const onStart = useCallback(
    (event: React.MouseEvent<HTMLSpanElement, MouseEvent>) => {
      // Update ref values directly, no re-render
      draggingRef.current = true;
      startValueRef.current = event.clientX;
      snapshotRef.current = value;
      document.documentElement.style.cursor = "ew-resize";
      document.body.style.pointerEvents = "none";
    },
    [value]
  );

  const onUpdate = useCallback(
    (event: PointerEvent) => {
      if (draggingRef.current) {
        const newDelta = (event.clientX - startValueRef.current) * speed;
        onValueChange(constrain(snapshotRef.current + newDelta));
      }
    },
    [constrain, speed, onValueChange]
  );

  const onEnd = useCallback(() => {
    draggingRef.current = false;
    document.documentElement.style.cursor = "";
    document.body.style.pointerEvents = "";
  }, []);

  useEffect(() => {
    document.addEventListener("pointermove", onUpdate);
    document.addEventListener("pointerup", onEnd);
    return () => {
      document.removeEventListener("pointermove", onUpdate);
      document.removeEventListener("pointerup", onEnd);
    };
  }, [onUpdate, onEnd]);

  return (
    <label
      className="flex touch-none items-center gap-2 px-1 py-0.5 align-middle text-lg focus-within:outline-2 focus-within:outline-blue-500"
      onClick={(e) => e.preventDefault()}
      title={title}
    >
      <span className="cursor-ew-resize" onPointerDown={onStart}>
        {children}
      </span>
      <input
        ref={inputRef}
        value={value}
        type="text"
        inputMode="numeric"
        pattern="[0-9]*"
        step={step}
        min={min}
        max={max}
        autoComplete="false"
        spellCheck="false"
        onBlur={(e) => onValueChange(constrain(parseInt(e.currentTarget.value, 10) || 0))}
        onKeyUp={(e) => {
          if (e.key === "Enter") {
            onValueChange(constrain(parseInt(e.currentTarget.value, 10) || 0));
            e.currentTarget.blur();
          }
        }}
        onClick={(e) => e.currentTarget.select()}
        onChange={(e) => onValueChange(+e.target.value)}
        {...props}
        className="w-full cursor-default border-0 focus-visible:outline-0"
      />
    </label>
  );
}

// src/components/DragInput.svelte
<script lang="ts">
  interface Props {
    value: number;
    min?: number | string;
    max?: number | string;
    step?: number | string;
    speed?: number;
    title?: string;
    class?: string;
    [key: string]: any;
  }

  let {
    value = $bindable(),
    min,
    max,
    step,
    speed = 1,
    title,
    class: className = '',
    children,
    ...restProps
  }: Props = $props();

  let inputElement: HTMLInputElement;
  let snapshot = $state(0);
  let startX = $state(0);
  let dragging = $state(false);

  // Helper functions for constraining the value
  const minValue = (val: number, minimum: number | string | undefined) =>
    minimum !== undefined ? Math.max(val, +Number(minimum)) : val;

  const maxValue = (val: number, maximum: number | string | undefined) =>
    maximum !== undefined ? Math.min(val, +Number(maximum)) : val;

  const stepValue = (val: number, stepSize: number | string | undefined) =>
    stepSize !== undefined && +Number(stepSize) !== 0
      ? Math.round(val / +Number(stepSize)) * +Number(stepSize)
      : val;

  const constrain = (val: number) =>
    maxValue(minValue(stepValue(val, step), min), max);

  // Drag handlers
  function handleDragStart(event: PointerEvent) {
    startX = event.clientX;
    snapshot = value;
    dragging = true;
    document.documentElement.style.cursor = 'ew-resize';
    document.body.style.pointerEvents = 'none';
  }

  function handleDragUpdate(event: PointerEvent) {
    if (dragging) {
      value = constrain(snapshot + (event.clientX - startX) * speed);
    }
  }

  function handleDragEnd() {
    dragging = false;
    document.documentElement.style.cursor = '';
    document.body.style.pointerEvents = '';
  }

  // Input field handlers
  function handleInputBlur(event: FocusEvent) {
    const target = event.currentTarget as HTMLInputElement;
    value = constrain(parseInt(target.value, 10) || 0);
  }

  function handleInputKeyup(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      const target = event.currentTarget as HTMLInputElement;
      value = constrain(parseInt(target.value, 10) || 0);
      target.blur();
    }
  }

  function handleInputClick(event: MouseEvent) {
    const target = event.currentTarget as HTMLInputElement;
    target.select();
  }

  function handleInputChange(event: Event) {
    const target = event.target as HTMLInputElement;
    value = +target.value;
  }

  // Keyboard navigation for button
  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      inputElement?.focus();
    }
  }
</script>

<div
  class="flex touch-none items-center gap-2 px-1 py-0.5 align-middle text-lg focus-within:outline-2 focus-within:outline-blue-500 {className}"
  {title}
  onpointermove={handleDragUpdate}
  onpointerup={handleDragEnd}
>
  <button
    type="button"
    class="cursor-ew-resize bg-transparent border-0 p-0"
    onpointerdown={handleDragStart}
    onkeydown={handleKeydown}
    aria-label="Drag to adjust value"
  >
    {@render children?.()}
  </button>
  <input
    bind:this={inputElement}
    bind:value
    type="text"
    inputmode="numeric"
    pattern="[0-9]*"
    {step}
    {min}
    {max}
    spellcheck="false"
    onblur={handleInputBlur}
    onkeyup={handleInputKeyup}
    onclick={handleInputClick}
    oninput={handleInputChange}
    {...restProps}
    class="w-full cursor-default border-0 focus-visible:outline-0"
  />
</div>
