// src/components/Text.tsx
import { useContent } from "@/features/content/store";
import { useNavbarStore } from "@/features/navbar/store";
import { clsx } from "@/lib/css";
import { escape } from "@/lib/html-escaper";
import { getBoundsStart } from "@/lib/speech-matcher";
import { getNextWordIndex, type Token as TokenType } from "@/lib/word-tokenizer";
import { memo, useMemo } from "react";

interface TextProps {
  style: React.CSSProperties;
  lastRef: React.RefObject<HTMLDivElement | null>;
}

export function Text({ style, lastRef }: TextProps) {
  const status = useNavbarStore(state => state.status);
  const mirror = useNavbarStore(state => state.mirror);
  const { tokens, position, setPosition } = useContent();
  const { start, end, bounds } = position;

  // Memoize all tokens to prevent unnecessary re-renders in the map function
  const memoizedTokens = useMemo(() => {
    return tokens.map((token, index) => {
      let className = "";
      if (token.index <= start) {
        className = "final-transcript";
      } else if (token.index <= end) {
        className = "interim-transcript";
      } else if (status === "started") {
        if (token.index > bounds + 20) {
          className = "opacity-40";
        } else if (token.index > bounds + 10) {
          className = "opacity-60";
        } else if (token.index > bounds) {
          className = "opacity-80";
        }
      }

      const isLastRef = index === Math.min(getNextWordIndex(tokens, end), tokens.length - 1);
      const ref = isLastRef ? (lastRef as React.RefObject<HTMLSpanElement>) : undefined;

      // Memoize click handler here
      const handleClick = () => {
        const selectedPosition = index - 1;
        const newBounds = getBoundsStart(tokens, selectedPosition);
        setPosition({
          start: selectedPosition,
          search: selectedPosition,
          end: selectedPosition,
          ...(newBounds !== undefined && {
            bounds: Math.min(newBounds, tokens.length),
          }),
        });
      };

      return (
        <Token
          key={token.index}
          token={token}
          className={className}
          ref={ref}
          onClick={handleClick}
        />
      );
    });
  }, [tokens, start, end, bounds, status, lastRef, setPosition]);

  return (
    <div
      className={clsx("content select-none", status === "started" ? "content-transition" : "")}
      style={{
        ...style,
        transform: `scaleX(${mirror ? "-1" : "1"})`,
      }}
    >
      {memoizedTokens}
    </div>
  );
}

interface TokenProps {
  token: TokenType;
  className: string;
  ref?: React.Ref<HTMLSpanElement>;
  onClick: () => void;
}

export const Token = memo<TokenProps>(
  ({ token, className, ref, onClick }) => {
    // Memoize the HTML content
    const htmlContent = useMemo(
      () => ({
        __html: escape(token.value).replace(/\n/g, "<br>"),
      }),
      [token.value],
    );

    return (
      <span
        ref={ref}
        key={token.index}
        onClick={onClick}
        className={className}
        dangerouslySetInnerHTML={htmlContent}
      />
    );
  },
  // Custom comparison to ensure memo works
  (prevProps, nextProps) => {
    return (
      prevProps.token.index === nextProps.token.index &&
      prevProps.token.value === nextProps.token.value &&
      prevProps.className === nextProps.className
    );
  },
);

Token.displayName = "Token";

// src/components/Text.svelte
<script lang="ts">
  import { contentStore } from "@/features/content/store.svelte";
  import { navbarStore } from "@/features/navbar/store.svelte";
  import { cn } from "@/lib/css";
  import { escape } from "@/lib/html-escaper";
  import { getBoundsStart } from "@/lib/speech-matcher";
  import { getNextWordIndex, type Token } from "@/lib/word-tokenizer";

  interface Props {
    style: Record<string, string | number>;
    lastRef?: HTMLSpanElement;
  }

  let { style, lastRef = $bindable() }: Props = $props();

  // Computed style object and convert to CSS string
  let computedStyleCSS = $derived(
    Object.entries({
      ...style,
      transform: `scaleX(${navbarStore.mirror ? "-1" : "1"})`,
    })
      .map(([key, value]) => `${key.replace(/[A-Z]/g, m => '-' + m.toLowerCase())}: ${value}`)
      .join('; ')
  );

  function handleTokenClick(index: number) {
    const selectedPosition = index - 1;
    const bounds = getBoundsStart(contentStore.tokens(), selectedPosition);
    contentStore.setPosition({
      start: selectedPosition,
      search: selectedPosition,
      end: selectedPosition,
      ...(bounds !== undefined && {
        bounds: Math.min(bounds, contentStore.tokens.length),
      }),
    });
  }

  function getTokenClassName(token: Token) {
    if (token.index <= contentStore.position().start) {
      return "final-transcript";
    }
    if (token.index <= contentStore.position().end) {
      return "interim-transcript";
    }
    if (navbarStore.status === "started") {
      if (token.index > contentStore.position().bounds + 20) {
        return "opacity-40";
      }
      if (token.index > contentStore.position().bounds + 10) {
        return "opacity-60";
      }
      if (token.index > contentStore.position().bounds) {
        return "opacity-80";
      }
    }
    return "";
  }

  function getTokenHTML(tokenValue: string) {
    return escape(tokenValue).replace(/\n/g, "<br>");
  }

  function handleTokenKeydown(event: KeyboardEvent, index: number) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      handleTokenClick(index);
    }
  }
</script>

<div
  class={cn("content select-none", navbarStore.status === "started" ? "content-transition" : "")}
  style={computedStyleCSS}
>
  {#each contentStore.tokens() as token, index (token.index)}
    {@const isLastRef = index === Math.min(getNextWordIndex(contentStore.tokens(), contentStore.position().end), contentStore.tokens().length - 1)}
    {#if isLastRef}
      <span
        bind:this={lastRef}
        class={getTokenClassName(token)}
        onclick={() => handleTokenClick(index)}
        onkeydown={(e) => handleTokenKeydown(e, index)}
        role="button"
        tabindex="0"
      >
        {@html getTokenHTML(token.value)}
      </span>
    {:else}
      <span
        class={getTokenClassName(token)}
        onclick={() => handleTokenClick(index)}
        onkeydown={(e) => handleTokenKeydown(e, index)}
        role="button"
        tabindex="0"
      >
        {@html getTokenHTML(token.value)}
      </span>
    {/if}
  {/each}
</div>
