// src/App.tsx
import { Navbar } from "./features/navbar";
import { Content } from "./features/content";
import { Capture } from "./features/capture";
import { Status } from "./features/status";
import { Collaborate } from "./features/collaborate";
import { isMobileOrTablet } from "./lib/device";

const mobileOrTablet = isMobileOrTablet();

const App = () => {
  return (
    <div className="app">
      <Status />
      <Navbar />
      {!mobileOrTablet && <Capture />}
      <Content />
      <Collaborate />
    </div>
  );
};

export default App;

// src/App.svelte
<script lang="ts">
  import Status from "./features/status.svelte";
  import Navbar from "./features/navbar/index.svelte";
  import Content from "./features/content/index.svelte";
  import Capture from "./features/capture/index.svelte";
  import Collaborate from "./features/collaborate/index.svelte";
  import { isMobileOrTablet } from "./lib/device";

  const mobileOrTablet = isMobileOrTablet();
</script>


<Status />
<Navbar />
{#if !mobileOrTablet}
  <Capture />
{/if}
<Content />
<Collaborate />
