// src/features/navbar/index.svelte
<script lang="ts">
  import { createFullscreen } from "@/app/fullscreen.svelte";
  import { recognizerStore } from "@/app/recognizer.svelte";
  import { navbarStore } from "./store.svelte";
  import { contentStore } from "../content/store.svelte";
  import { collaborateStore } from "../collaborate/store.svelte";
  import * as Tooltip from "@/components/tooltip/index.js";
  import {
    Pencil,
    MoveHorizontal,
    Play,
    Pause,
    Expand,
    Trash2,
    AArrowUp,
    Minimize2,
    Sun,
    TextAlignCenter,
    SunDim,
    SunMedium,
    Undo2,
    MonitorUp,
    UsersRound,
  } from "lucide-svelte";
  import DragInput from "@/components/DragInput.svelte";
  import { cn } from "@/lib/css";
  import { isMobileOrTablet } from "@/lib/device";
  import { getBoundsStart, resetTranscriptWindow } from "@/lib/speech-matcher";

  const mobileOrTablet = isMobileOrTablet();

  // Create fullscreen handler
  const fullscreen = createFullscreen((active) => navbarStore.setHide(active));

  // Focus tracking for hotkeys
  let focused = $state(false);

  // Timer effect - runs when status is "started"
  let timerInterval: number | undefined = $state();

  $effect(() => {
    if (navbarStore.status === "started") {
      timerInterval = setInterval(navbarStore.incrementTimer, 1000);
    } else {
      if (timerInterval) {
        clearInterval(timerInterval);
        timerInterval = undefined;
      }
    }

    // Cleanup on unmount
    return () => {
      if (timerInterval) {
        clearInterval(timerInterval);
      }
    };
  });

  // Hotkey handlers
  function handleKeydown(event: KeyboardEvent) {
    if (focused || navbarStore.status === "editing") return; // Don't trigger when focused on inputs

    switch (event.code) {
      case "Space":
        if (navbarStore.status !== "editing") {
          event.preventDefault();
          navbarStore.status === "stopped" ? recognizerStore.startTeleprompter() : recognizerStore.stopTeleprompter();
        }
        break;
      case "Escape":
        if (navbarStore.status === "started") {
          recognizerStore.stopTeleprompter();
        }
        break;
      case "KeyE":
        if (navbarStore.status !== "started") {
          navbarStore.toggleEdit();
        }
        break;
      case "Delete":
        if (navbarStore.status !== "started") {
          if (confirm("Are you sure you want to clear your script?")) {
            contentStore.setText("");
          }
        }
        break;
      case "KeyM":
        if (navbarStore.status !== "editing") {
          navbarStore.toggleMirror();
        }
        break;
      case "KeyF":
        fullscreen.active ? fullscreen.exit() : fullscreen.enter();
        break;
      case "KeyH":
        navbarStore.setHide(!navbarStore.hide);
        break;
      case "KeyS":
        if (!mobileOrTablet) {
          navbarStore.setCast(!navbarStore.cast);
        }
        break;
      case "KeyR":
        if (navbarStore.status !== "editing") {
          handleRestart();
        }
        break;
      case "KeyT":
        navbarStore.setAlign("top");
        break;
      case "KeyC":
        navbarStore.setAlign("center");
        break;
      case "KeyB":
        navbarStore.setAlign("bottom");
        break;
      case "Equal":
      case "Minus":
        handleFontSizeShortcut(event);
        break;
      case "BracketLeft":
      case "BracketRight":
        handleMarginShortcut(event);
        break;
      case "Semicolon":
      case "Quote":
        handleOpacityShortcut(event);
        break;
    }
  }

  function handleFontSizeShortcut(event: KeyboardEvent) {
    const step = 5;
    const current = navbarStore.fontSize;
    if (event.code === "Equal") {
      navbarStore.setFontSize(Math.min(current + step, 150));
    } else {
      navbarStore.setFontSize(Math.max(current - step, 15));
    }
  }

  function handleMarginShortcut(event: KeyboardEvent) {
    const step = 2;
    const current = navbarStore.margin;
    if (event.code === "BracketRight") {
      navbarStore.setMargin(Math.min(current + step, 44));
    } else {
      navbarStore.setMargin(Math.max(current - step, 0));
    }
  }

  function handleOpacityShortcut(event: KeyboardEvent) {
    const step = 10;
    const current = navbarStore.opacity;
    if (event.code === "Quote") {
      navbarStore.setOpacity(Math.min(current + step, 100));
    } else {
      navbarStore.setOpacity(Math.max(current - step, 20));
    }
  }

  function handleRestart() {
    const selectedPosition = -1;
    const boundStart = getBoundsStart(contentStore.tokens(), 0);
    contentStore.setPosition({
      start: selectedPosition,
      end: selectedPosition,
      search: selectedPosition,
      ...(boundStart !== undefined && { bounds: boundStart }),
    });
    navbarStore.resetTimer();
    resetTranscriptWindow();
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  // Format timer display
  const formattedTimer = $derived(
    `${Math.floor(navbarStore.timer / (60 * 60)).toString().padStart(2, "0")}:${Math.floor((navbarStore.timer / 60) % 60).toString().padStart(2, "0")}:${(navbarStore.timer % 60).toString().padStart(2, "0")}`
  );

  // Brightness icon based on opacity
  const BrightnessIcon = $derived(
    navbarStore.opacity > 80 ? Sun :
    navbarStore.opacity > 50 ? SunMedium :
    SunDim
  );
</script>

<svelte:window onkeydown={handleKeydown} />

<nav
  aria-label="main navigation"
  class={cn(
    "top-0 z-10 flex w-full flex-wrap items-center justify-evenly gap-x-4 gap-y-1 border-b border-neutral-800 bg-neutral-950/90 px-3 py-2 text-white backdrop-blur transition select-none hover:opacity-100 min-[925px]:justify-between",
    navbarStore.hide ? "fixed -translate-y-full" : "sticky translate-y-0",
  )}
>
  <Tooltip.Provider>
    <!-- Button Section -->
    <div
      class="flex flex-wrap items-center gap-x-1"
      onfocus={() => (focused = true)}
      onblur={() => (focused = false)}
    >
      <!-- Start/Stop Button -->
      <Tooltip.Root>
        <Tooltip.Trigger
          type="button"
          class={cn(
            "button group/button flex items-center gap-2 rounded-md disabled:border-neutral-900 disabled:bg-transparent hover:disabled:border-neutral-900 hover:disabled:bg-transparent sm:mr-1 sm:border",
            navbarStore.status === "started"
              ? "sm:border-red-500/30 sm:bg-red-700/10 sm:hover:border-red-500/40 sm:hover:bg-red-700/20"
              : "sm:border-green-500/30 sm:bg-green-700/10 sm:hover:border-green-500/40 sm:hover:bg-green-700/20",
          )}
          disabled={navbarStore.status === "editing"}
          onclick={() => navbarStore.status === "stopped" ? recognizerStore.startTeleprompter() : recognizerStore.stopTeleprompter()}
          aria-label={navbarStore.status === "started" ? "Stop" : "Start"}
        >
          {#if navbarStore.status === "stopped" || navbarStore.status === "editing"}
            <Play class={`icon ${navbarStore.status !== "editing" && "green-fill"}`} />
          {:else}
            <Pause class="icon red-fill" />
          {/if}
          <span
            class={cn(
              "hidden pr-1 group-disabled/button:text-neutral-800 sm:inline",
              navbarStore.status === "started"
                ? "pr-1.5 text-red-300/90 group-hover/button:text-red-300"
                : "pr-1 text-green-300/80 group-hover/button:text-green-300/90",
            )}
          >
            {navbarStore.status === "started" ? "Stop " : "Start"}
          </span>
        </Tooltip.Trigger>
        <Tooltip.Content>
          {navbarStore.status === "started" ? "Stop" : "Start"} <kbd>Space</kbd>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Edit Button -->
      <Tooltip.Root>
        <Tooltip.Trigger
          type="button"
          class="button"
          onclick={() => {
            navbarStore.toggleEdit();

          }}
          disabled={navbarStore.status === "started"}
          aria-label="Edit Text"
        >
          <Pencil class={`icon ${navbarStore.status === "editing" ? "yellow" : ""}`} />
        </Tooltip.Trigger>
        <Tooltip.Content>
          Edit <kbd>E</kbd>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Reset Button -->
      <Tooltip.Root>
        <Tooltip.Trigger
          type="button"
          class="button"
          onclick={handleRestart}
          disabled={navbarStore.status === "editing"}
          aria-label="Reset to Top"
        >
          <Undo2 class="icon" />
        </Tooltip.Trigger>
        <Tooltip.Content>
          Reset to Top <kbd>R</kbd>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Clear Button -->
      <Tooltip.Root>
        <Tooltip.Trigger
          type="button"
          class="button"
          onclick={() => {
            if (confirm("Are you sure you want to clear your script?")) {
              contentStore.setText("");
  
            }
          }}
          disabled={navbarStore.status === "started"}
          aria-label="Clear Text"
        >
          <Trash2 class="icon" />
        </Tooltip.Trigger>
        <Tooltip.Content>
          Clear <kbd>Del</kbd>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Mirror Button -->
      <Tooltip.Root>
        <Tooltip.Trigger
          type="button"
          class="button"
          onclick={() => navbarStore.toggleMirror()}
          disabled={navbarStore.status === "editing"}
          aria-label="Mirror"
        >
          <MoveHorizontal class={`icon ${navbarStore.mirror ? "yellow" : ""}`} />
        </Tooltip.Trigger>
        <Tooltip.Content>
          Mirror <kbd>M</kbd>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Fullscreen Button -->
      <Tooltip.Root>
        <Tooltip.Trigger
          type="button"
          class="button"
          onclick={() => fullscreen.active ? fullscreen.exit() : fullscreen.enter()}
          aria-label={fullscreen.active ? "Exit Fullscreen" : "Fullscreen"}
        >
          <Expand class={`icon ${fullscreen.active ? "yellow" : ""}`} />
        </Tooltip.Trigger>
        <Tooltip.Content>
          {fullscreen.active ? "Exit Fullscreen" : "Fullscreen"} <kbd>F</kbd>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Cast Screen Button -->
      {#if !mobileOrTablet}
        <Tooltip.Root>
          <Tooltip.Trigger
            type="button"
            class="button"
            onclick={() => navbarStore.setCast(!navbarStore.cast)}
            aria-label={navbarStore.cast ? "Stop Casting" : "Cast Screen"}
          >
            <MonitorUp class={`icon ${navbarStore.cast ? "yellow" : ""}`} />
          </Tooltip.Trigger>
          <Tooltip.Content>
            {navbarStore.cast ? "Stop Casting" : "Cast Screen"} <kbd>S</kbd>
          </Tooltip.Content>
        </Tooltip.Root>
      {/if}

      <!-- Collaborate Button -->
      <Tooltip.Root>
        <Tooltip.Trigger
          type="button"
          class="button"
          onclick={() => navbarStore.setCollaborate(true)}
          aria-label="Collaborate"
        >
          <UsersRound class={`icon ${collaborateStore.isConnected ? "yellow" : ""}`} />
        </Tooltip.Trigger>
        <Tooltip.Content>
          {collaborateStore.isConnected ? "Connected to Room" : "Collaborate"}
        </Tooltip.Content>
      </Tooltip.Root>
    </div>

    <!-- Timer Section -->
    <div class="flex justify-center text-3xl text-neutral-300 max-[1000px]:hidden">
      <span>{formattedTimer}</span>
    </div>

    <!-- Slider Section -->
    <div
      class="flex flex-wrap items-center justify-center gap-x-4 gap-y-0.5 text-neutral-300 lg:justify-end"
      onfocus={() => (focused = true)}
      onblur={() => (focused = false)}
    >
      <!-- Font Size -->
      <Tooltip.Root>
        <Tooltip.Trigger>
          <div class="w-20">
            <DragInput
              bind:value={navbarStore.fontSize}
              step={5}
              min={15}
              max={150}
              aria-label="Font Size"
            >
              <AArrowUp class="size-7" />
            </DragInput>
          </div>
        </Tooltip.Trigger>
        <Tooltip.Content>
          Font Size <span class="text-neutral-400"><kbd>-</kbd><kbd>+</kbd></span>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Margin -->
      <Tooltip.Root>
        <Tooltip.Trigger>
          <div class="w-[4.75rem]">
            <DragInput
              bind:value={navbarStore.margin}
              step={2}
              min={0}
              max={44}
              speed={0.5}
              aria-label="Margin"
            >
              <Minimize2 class="size-7 rotate-45" />
            </DragInput>
          </div>
        </Tooltip.Trigger>
        <Tooltip.Content>
          Margin <span class="text-neutral-400"><kbd>{"["}</kbd><kbd>{"]"}</kbd></span>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Brightness -->
      <Tooltip.Root>
        <Tooltip.Trigger>
          <div class="w-20">
            <DragInput
              bind:value={navbarStore.opacity}
              step={10}
              min={20}
              max={100}
              aria-label="Brightness"
            >
              <BrightnessIcon />
            </DragInput>
          </div>
        </Tooltip.Trigger>
        <Tooltip.Content>
          Brightness <span class="text-neutral-400"><kbd>;</kbd><kbd>'</kbd></span>
        </Tooltip.Content>
      </Tooltip.Root>

      <!-- Align -->
      <div>
        <Tooltip.Root>
          <Tooltip.Trigger>
            <label
              class="flex gap-1 px-1 focus-within:outline-2 focus-within:outline-blue-500"
              aria-label="Align"
            >
              <TextAlignCenter />
              <select
                class="border-0 focus-visible:outline-0"
                bind:value={navbarStore.align}
              >
                <option class="bg-black" value="top">Top</option>
                <option class="bg-black" value="center">Center</option>
                <option class="bg-black" value="bottom">Bottom</option>
              </select>
            </label>
          </Tooltip.Trigger>
          <Tooltip.Content>
            Align <span class="text-neutral-400"><kbd>T</kbd><kbd>C</kbd><kbd>B</kbd></span>
          </Tooltip.Content>
        </Tooltip.Root>
      </div>
    </div>

    <!-- Hide/Show Toggle Button -->
    <button
      type="button"
      onclick={() => navbarStore.setHide(!navbarStore.hide)}
      aria-label="Toggle navbar visibility"
      class="group absolute -bottom-4 left-1/2 z-20 flex h-8 w-2/3 -translate-x-1/2 translate-y-1/2 justify-center p-1 hover:cursor-pointer focus:outline-0"
    >
      <div class="h-2 w-1/2 rounded-full transition delay-75 group-hover:bg-neutral-700/85 group-focus:bg-neutral-700/85 group-focus:outline-2 group-active:bg-neutral-700/85"></div>
    </button>
  </Tooltip.Provider>
</nav>

// src/features/navbar/index.tsx
import { useFullScreen } from "@/app/hooks";
import { startTeleprompter, stopTeleprompter } from "@/app/recognizer";
import { Align, useNavbarStore } from "./store";
import { useContent } from "../content/store";
import { useCollaborateStore } from "../collaborate/store";
import { useInterval } from "@/app/hooks";
import { Tooltip } from "@base-ui-components/react/tooltip";
import {
  Pencil,
  MoveHorizontal,
  Play,
  Pause,
  Expand,
  Trash2,
  AArrowUp,
  Minimize2,
  Sun,
  AlignCenter,
  SunDim,
  SunMedium,
  Undo2,
  MonitorUp,
  UsersRound,
} from "lucide-react";
import { useHotkeys } from "react-hotkeys-hook";
import { useState } from "react";
import { DragInput } from "@/components/DragInput";
import { clsx } from "@/lib/css";
import { isMobileOrTablet } from "@/lib/device";
import { getBoundsStart, resetTranscriptWindow } from "@/lib/speech-matcher";
import { TooltipPopup } from "@/components/Tooltip";

const mobileOrTablet = isMobileOrTablet();

export function Navbar() {
  const [focused, setFocused] = useState(false);
  const hide = useNavbarStore((state) => state.hide);
  const setHide = useNavbarStore((state) => state.setHide);

  return (
    <nav
      role="navigation"
      aria-label="main navigation"
      className={clsx(
        "top-0 z-10 flex w-full flex-wrap items-center justify-evenly gap-x-4 gap-y-1 border-b border-neutral-800 bg-neutral-950/90 px-3 py-2 text-white backdrop-blur transition select-none hover:opacity-100 min-[925px]:justify-between",
        hide ? "fixed -translate-y-full" : "sticky translate-y-0",
      )}
    >
      <Tooltip.Provider>
        <div
          className="flex flex-wrap items-center gap-x-1"
          onFocus={() => setFocused(() => true)}
          onBlur={() => setFocused(() => false)}
        >
          <ButtonSection focused={focused} />
        </div>
        <div className="flex justify-center text-3xl text-neutral-300 max-[1000px]:hidden">
          <TimerSection />
        </div>
        <div
          className="flex flex-wrap items-center justify-center gap-x-4 gap-y-0.5 text-neutral-300 lg:justify-end"
          onFocus={() => setFocused(() => true)}
          onBlur={() => setFocused(() => false)}
        >
          <SliderSection />
        </div>
        <button
          type="button"
          onClick={() => setHide(!hide)}
          className="group absolute -bottom-4 left-1/2 z-20 flex h-8 w-2/3 -translate-x-1/2 translate-y-1/2 justify-center p-1 hover:cursor-pointer focus:outline-0"
        >
          <div className="h-2 w-1/2 rounded-full transition delay-75 group-hover:bg-neutral-700/85 group-focus:bg-neutral-700/85 group-focus:outline-2 group-active:bg-neutral-700/85"></div>
        </button>
      </Tooltip.Provider>
    </nav>
  );
}

function ButtonSection({ focused }: { focused: boolean }) {
  const {
    status,
    toggleEdit,
    mirror,
    toggleMirror,
    resetTimer,
    hide,
    setHide,
    cast,
    setCast,
    setCollaborate: setCollaborateOpen,
  } = useNavbarStore((state) => state);

  const { isConnected } = useCollaborateStore();

  const { setText: setContent, tokens, setTokens, setPosition } = useContent();

  const fullscreen = useFullScreen((active) => setHide(active));

  const startAction = {
    action: () => (status === "stopped" ? startTeleprompter() : stopTeleprompter()),
    disabled: status === "editing",
    keys: [],
  };

  useHotkeys(
    "space",
    startAction.action,
    { enabled: !startAction.disabled && !focused, preventDefault: true },
    [startAction.action, focused],
  );

  useHotkeys(
    "esc",
    startAction.action,
    {
      enabled: status === "started",
    },
    [status, stopTeleprompter],
  );

  const editAction = {
    action: () => (toggleEdit(), setTokens()),
    disabled: status === "started",
    keys: ["e"],
  };
  useActionHotkeys(editAction);

  const clearAction = {
    action: () => {
      if (confirm("Are you sure you want to clear your script?")) {
        setContent("");
        setTokens();
      }
    },
    disabled: status === "started",
    keys: ["delete"],
  };
  useActionHotkeys(clearAction);

  const mirrorAction = {
    action: () => toggleMirror(),
    disabled: status === "editing",
    keys: ["m"],
  };
  useActionHotkeys(mirrorAction);

  const fullscreenAction = {
    action: () => (fullscreen.active ? fullscreen.exit() : fullscreen.enter()),
    disabled: false,
    keys: ["f"],
  };
  useActionHotkeys(fullscreenAction);

  const hideAction = {
    action: () => setHide(!hide),
    disabled: false,
    keys: ["h"],
  };
  useActionHotkeys(hideAction);

  const castScreenAction = {
    action: () => setCast(!cast),
    disabled: false,
    keys: ["s"],
  };
  useActionHotkeys(castScreenAction);

  const restartAction = {
    action: () => {
      const selectedPosition = -1;
      const boundStart = getBoundsStart(tokens, 0);
      setPosition({
        start: selectedPosition,
        end: selectedPosition,
        search: selectedPosition,
        ...(boundStart !== undefined && { bounds: boundStart }),
      });
      resetTimer();
      resetTranscriptWindow();
      window.scrollTo({ top: 0, behavior: "smooth" });
    },
    disabled: status === "editing",
    keys: ["r"],
  };
  useActionHotkeys(restartAction);

  return (
    <>
      <Tooltip.Root aria-disabled={startAction.disabled || mobileOrTablet}>
        <Tooltip.Trigger
          type="button"
          className={clsx(
            "button group/button flex items-center gap-2 rounded-md disabled:border-neutral-900 disabled:bg-transparent hover:disabled:border-neutral-900 hover:disabled:bg-transparent sm:mr-1 sm:border",
            status === "started"
              ? "sm:border-red-500/30 sm:bg-red-700/10 sm:hover:border-red-500/40 sm:hover:bg-red-700/20"
              : "sm:border-green-500/30 sm:bg-green-700/10 sm:hover:border-green-500/40 sm:hover:bg-green-700/20",
          )}
          disabled={startAction.disabled}
          onClick={startAction.action}
          aria-label={status === "started" ? "Stop" : "Start"}
        >
          {status === "stopped" || status === "editing" ? (
            <Play className={`icon ${status !== "editing" && "green-fill"}`} />
          ) : (
            <Pause className="icon red-fill" />
          )}
          <span
            className={clsx(
              "hidden pr-1 group-disabled/button:text-neutral-800 sm:inline",
              status === "started"
                ? "pr-1.5 text-red-300/90 group-hover/button:text-red-300"
                : "pr-1 text-green-300/80 group-hover/button:text-green-300/90",
            )}
          >
            {status === "started" ? "Stop " : "Start"}
          </span>
        </Tooltip.Trigger>
        <TooltipPopup>
          {status === "started" ? "Stop" : "Start"} <kbd>Space</kbd>
        </TooltipPopup>
      </Tooltip.Root>
      <Tooltip.Root aria-disabled={editAction.disabled || mobileOrTablet}>
        <Tooltip.Trigger
          type="button"
          className="button"
          onClick={editAction.action}
          disabled={editAction.disabled}
          aria-label="Edit Text"
        >
          <Pencil className={`icon ${status === "editing" ? "yellow" : ""}`} />
        </Tooltip.Trigger>
        <TooltipPopup>
          Edit <kbd>E</kbd>
        </TooltipPopup>
      </Tooltip.Root>
      <Tooltip.Root aria-disabled={restartAction.disabled || mobileOrTablet}>
        <Tooltip.Trigger
          className="button"
          onClick={restartAction.action}
          disabled={restartAction.disabled}
          aria-label="Reset to Top"
        >
          <Undo2 className="icon" />
        </Tooltip.Trigger>
        <TooltipPopup>
          Reset to Top <kbd>R</kbd>
        </TooltipPopup>
      </Tooltip.Root>
      <Tooltip.Root aria-disabled={clearAction.disabled || mobileOrTablet}>
        <Tooltip.Trigger
          type="button"
          className="button"
          onClick={clearAction.action}
          disabled={clearAction.disabled}
          aria-label="Clear Text"
        >
          <Trash2 className="icon" />
        </Tooltip.Trigger>
        <TooltipPopup>
          Clear <kbd>Del</kbd>
        </TooltipPopup>
      </Tooltip.Root>
      <Tooltip.Root aria-disabled={mirrorAction.disabled || mobileOrTablet}>
        <Tooltip.Trigger
          type="button"
          className="button"
          onClick={mirrorAction.action}
          disabled={mirrorAction.disabled}
          aria-label="Mirror"
        >
          <MoveHorizontal className={`icon ${mirror ? "yellow" : ""}`} />
        </Tooltip.Trigger>
        <TooltipPopup>
          Mirror <kbd>M</kbd>
        </TooltipPopup>
      </Tooltip.Root>
      <Tooltip.Root aria-disabled={fullscreenAction.disabled || mobileOrTablet}>
        <Tooltip.Trigger
          type="button"
          className="button"
          onClick={fullscreenAction.action}
          disabled={fullscreenAction.disabled}
          aria-label={fullscreen.active ? "Exit Fullscreen" : "Fullscreen"}
        >
          <Expand className={`icon ${fullscreen.active ? "yellow" : ""}`} />
        </Tooltip.Trigger>
        <TooltipPopup>
          {fullscreen.active ? "Exit Fullscreen" : "Fullscreen"} <kbd>F</kbd>
        </TooltipPopup>
      </Tooltip.Root>
      {!mobileOrTablet && (
        <Tooltip.Root aria-disabled={castScreenAction.disabled || mobileOrTablet}>
          <Tooltip.Trigger
            className="button"
            onClick={castScreenAction.action}
            disabled={castScreenAction.disabled}
            aria-label={cast ? "Stop Casting" : "Cast Screen"}
          >
            <MonitorUp className={`icon ${cast ? "yellow" : ""}`} />
          </Tooltip.Trigger>
          <TooltipPopup>
            {cast ? "Stop Casting" : "Cast Screen"} <kbd>S</kbd>
          </TooltipPopup>
        </Tooltip.Root>
      )}
      <Tooltip.Root>
        <Tooltip.Trigger
          type="button"
          className="button"
          onClick={() => setCollaborateOpen(true)}
          aria-label="Collaborate"
        >
          <UsersRound className={`icon ${isConnected() ? "yellow" : ""}`} />
        </Tooltip.Trigger>
        <TooltipPopup>{isConnected() ? "Connected to Room" : "Collaborate"}</TooltipPopup>
      </Tooltip.Root>
    </>
  );
}

function TimerSection() {
  const status = useNavbarStore((state) => state.status);
  const timer = useNavbarStore((state) => state.timer);
  const incrementTimer = useNavbarStore((state) => state.incrementTimer);

  useInterval(() => incrementTimer(), status === "started" ? 1000 : null);

  return (
    <span>
      {Math.floor(timer / (60 * 60))
        .toString()
        .padStart(2, "0")}
      :
      {Math.floor((timer / 60) % 60)
        .toString()
        .padStart(2, "0")}
      :{(timer % 60).toString().padStart(2, "0")}
    </span>
  );
}

function SliderSection() {
  const { fontSize, setFontSize, margin, setMargin, opacity, setOpacity, align, setAlign } =
    useNavbarStore((state) => state);

  const sizeSlider = {
    step: 5,
    min: 15,
    max: 150,
    value: fontSize,
    action: setFontSize,
    incrementKeys: ["Equal", "ctrl+shift+period"],
    decrementKeys: ["Minus", "ctrl+shift+comma"],
  };
  useSliderHotkeys(sizeSlider);

  const marginSlider = {
    step: 2,
    min: 0,
    max: 44,
    value: margin,
    action: setMargin,
    incrementKeys: ["BracketRight"],
    decrementKeys: ["BracketLeft"],
  };
  useSliderHotkeys(marginSlider);

  const contrastSlider = {
    step: 10,
    min: 20,
    max: 100,
    value: opacity,
    action: setOpacity,
    incrementKeys: ["Quote"],
    decrementKeys: ["Semicolon"],
  };
  useSliderHotkeys(contrastSlider);

  useHotkeys("t", () => setAlign("top"));
  useHotkeys("c", () => setAlign("center"));
  useHotkeys("b", () => setAlign("bottom"));

  return (
    <>
      <Tooltip.Root aria-disabled={mobileOrTablet}>
        <Tooltip.Trigger
          render={(props) => (
            <div {...props} className="w-20">
              <DragInput
                value={sizeSlider.value}
                onValueChange={sizeSlider.action}
                step={sizeSlider.step}
                min={sizeSlider.min}
                max={sizeSlider.max}
                aria-label="Font Size"
              >
                <AArrowUp className="size-7" />
              </DragInput>
            </div>
          )}
        />
        <TooltipPopup>
          Font Size{" "}
          <span className="text-neutral-400">
            <kbd>-</kbd>
            <kbd>+</kbd>
          </span>
        </TooltipPopup>
      </Tooltip.Root>
      <Tooltip.Root aria-disabled={mobileOrTablet}>
        <Tooltip.Trigger
          render={(props) => (
            <div {...props} className="w-[4.75rem]">
              <DragInput
                value={marginSlider.value}
                onValueChange={marginSlider.action}
                step={marginSlider.step}
                min={marginSlider.min}
                max={marginSlider.max}
                speed={0.5}
                aria-label="Margin"
              >
                <Minimize2 className="size-7 rotate-45" />
              </DragInput>
            </div>
          )}
        />
        <TooltipPopup>
          Margin{" "}
          <span className="text-neutral-400">
            <kbd>{"["}</kbd>
            <kbd>{"]"}</kbd>
          </span>
        </TooltipPopup>
      </Tooltip.Root>
      <Tooltip.Root aria-disabled={mobileOrTablet}>
        <Tooltip.Trigger
          render={(props) => (
            <div {...props} className="w-20">
              <DragInput
                value={contrastSlider.value}
                onValueChange={contrastSlider.action}
                step={contrastSlider.step}
                min={contrastSlider.min}
                max={contrastSlider.max}
                aria-label="Brightness"
              >
                {contrastSlider.value > 80 ? (
                  <Sun />
                ) : contrastSlider.value > 50 ? (
                  <SunMedium />
                ) : (
                  <SunDim />
                )}
              </DragInput>
            </div>
          )}
        />
        <TooltipPopup>
          Brightness{" "}
          <span className="text-neutral-400">
            <kbd>;</kbd>
            <kbd>'</kbd>
          </span>
        </TooltipPopup>
      </Tooltip.Root>
      <div>
        <Tooltip.Root aria-disabled={mobileOrTablet}>
          <Tooltip.Trigger
            render={(props) => (
              <label
                {...props}
                className="flex gap-1 px-1 focus-within:outline-2 focus-within:outline-blue-500"
                aria-label="Align"
              >
                <AlignCenter />
                <select
                  className="border-0 focus-visible:outline-0"
                  onChange={(e) => setAlign(e.target.value as Align)}
                  value={align}
                >
                  <option className="bg-black" value="top">
                    Top
                  </option>
                  <option className="bg-black" value="center">
                    Center
                  </option>
                  <option className="bg-black" value="bottom">
                    Bottom
                  </option>
                </select>
              </label>
            )}
          />

          <TooltipPopup>
            Align{" "}
            <span className="text-neutral-400">
              <kbd>T</kbd>
              <kbd>C</kbd>
              <kbd>B</kbd>
            </span>
          </TooltipPopup>
        </Tooltip.Root>
      </div>
    </>
  );
}

function useActionHotkeys({
  action,
  disabled,
  keys,
}: {
  action: () => void;
  disabled: boolean;
  keys: string[];
}) {
  useHotkeys(keys, action, { enabled: !disabled }, [action, disabled]);
}

function useSliderHotkeys({
  step,
  min,
  max,
  value,
  action,
  incrementKeys,
  decrementKeys,
}: {
  step: number;
  min: number;
  max: number;
  value: number;
  action: (value: number) => void;
  incrementKeys: string[];
  decrementKeys: string[];
}) {
  useHotkeys(incrementKeys, () => action(value + step <= max ? value + step : value), [
    incrementKeys,
    action,
    value,
    step,
    max,
  ]);
  useHotkeys(decrementKeys, () => action(value - step >= min ? value - step : value), [
    decrementKeys,
    action,
    value,
    step,
    max,
  ]);
}
